import Image from "next/image";
import {CalendarDays,MapPin,Search,Users} from "lucide-react";
import type {Dictionary,IndustryCopy,Locale} from "@/lib/i18n";
import {LocalizedLink} from "@/components/LocalizedLink";

export function TourismHero({d,visual,locale}:{d:IndustryCopy;visual:Dictionary["tourismVisual"];locale:Locale}){
 return <section className="tourism-hero hero-shell grid gap-10 lg:grid-cols-[.86fr_1.14fr] lg:items-center xl:gap-16">
  <div className="relative z-10 max-w-xl"><p className="eyebrow">{d.badge}</p><h1>{d.title}</h1><p className="hero-copy">{d.subtitle}</p><div className="hero-actions"><a href="#tourism-destinations">{d.heroPrimary}</a><LocalizedLink locale={locale} href="/contact?industry=tourism">{d.heroSecondary}</LocalizedLink></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[#9dc6c2]">{visual.heroTrust.map(item=><span key={item} className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#F13024]"/>{item}</span>)}</div></div>
  <div className="relative pb-10 sm:pr-5"><div aria-hidden="true" className="tourism-map-grid absolute -inset-6 rounded-[2.5rem]"/><div className="group relative aspect-[5/4] overflow-hidden rounded-[2rem] border border-white/15 bg-[#0a3037] shadow-[0_38px_100px_rgba(0,0,0,.35)]"><Image src="/images/industries/tourism/mountain-adventure-hero.avif" alt={visual.heroAlt} fill priority sizes="(max-width: 1023px) calc(100vw - 2rem), 56vw" className="object-cover object-[48%_50%] transition-transform duration-700 ease-out group-hover:scale-[1.015]"/><div className="absolute inset-0 bg-linear-to-t from-[#021a22]/75 via-transparent to-[#031a20]/10"/><svg aria-hidden="true" viewBox="0 0 520 360" className="tourism-route absolute inset-0 h-full w-full"><path d="M60 285 C130 220 158 290 218 222 S322 210 366 135 S430 92 470 65"/><circle cx="60" cy="285" r="7"/><circle cx="470" cy="65" r="8"/></svg></div>
   <div className="tourism-planner absolute -bottom-1 left-3 right-0 rounded-2xl border border-white/30 bg-[#f8f5ed]/95 p-4 text-[#102d35] shadow-2xl backdrop-blur-xl sm:left-auto sm:w-[26rem]"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#167b78]">{visual.plannerLabel}</p><p className="mt-1 font-semibold">{visual.plannerTitle}</p></div><span className="rounded-full bg-[#e1f1ed] px-2.5 py-1 text-[10px] font-bold text-[#167b78]">{visual.plannerState}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span><MapPin size={14}/>{visual.destination}</span><span><CalendarDays size={14}/>{visual.dates}</span><span><Users size={14}/>{visual.guests}</span><button type="button" aria-label={visual.searchTour}><Search size={15}/>{visual.searchTour}</button></div></div>
  </div>
 </section>;
}
