import Image from "next/image";
import {ArrowRight,CheckCircle2,MessageSquareText,UserRoundCheck} from "lucide-react";
import type {Dictionary} from "@/lib/i18n";
import {AiAutomationReveal} from "./AiAutomationReveal";

export function AiAssistants({visual}:{visual:Dictionary["aiAutomationVisual"]}){
 const cards=[{image:"/images/industries/ai-automation/ai-sales-automation.webp",alt:visual.salesAlt,eyebrow:visual.salesEyebrow,title:visual.salesTitle,text:visual.salesText,items:visual.salesItems,boundary:visual.salesBoundary},{image:"/images/industries/ai-automation/ai-support-assistant.jpg",alt:visual.supportAlt,eyebrow:visual.supportEyebrow,title:visual.supportTitle,text:visual.supportText,items:visual.supportItems,boundary:visual.supportBoundary}];
 return <AiAutomationReveal className="ai-automation-section"><div className="grid gap-5 lg:grid-cols-2">{cards.map((card,cardIndex)=><article key={card.title} className="overflow-hidden rounded-[2rem] border border-white/12 bg-[#0d152b]"><figure className="relative min-h-[18rem] overflow-hidden"><Image src={card.image} alt={card.alt} fill sizes="(max-width: 1023px) calc(100vw - 2rem), 50vw" className="object-cover object-center"/><div className="absolute inset-0 bg-linear-to-t from-[#0d152b] via-transparent to-transparent"/></figure><div className="p-6 pt-2 sm:p-8 sm:pt-2"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#63d8e7]">{card.eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">{card.title}</h2><p className="mt-4 leading-7 text-[#9eacc5]">{card.text}</p><div className="mt-6 space-y-2">{card.items.map((item,index)=><div key={item} className="flex items-center gap-3 rounded-xl border border-white/9 bg-white/4 p-3 text-sm"><CheckCircle2 size={16} className="shrink-0 text-[#776bf0]"/><span>{item}</span>{index===card.items.length-1&&(cardIndex===0?<UserRoundCheck className="ml-auto text-[#63d8e7]" size={16}/>:<MessageSquareText className="ml-auto text-[#63d8e7]" size={16}/>)}</div>)}</div><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-[#f1a07a]"><ArrowRight size={14}/>{card.boundary}</div></div></article>)}</div></AiAutomationReveal>;
}
