import Image from "next/image";
import {Building2,CalendarDays,CheckCircle2,Clock3,Stethoscope} from "lucide-react";
import type {Dictionary,IndustryCopy,Locale} from "@/lib/i18n";
import {LocalizedLink} from "@/components/LocalizedLink";

export function HealthcareHero({d,visual,locale}:{d:IndustryCopy;visual:Dictionary["healthcareVisual"];locale:Locale}){
 return <section className="healthcare-hero hero-shell grid gap-11 lg:grid-cols-[.88fr_1.12fr] lg:items-center xl:gap-16">
  <div className="relative z-10 max-w-xl"><p className="eyebrow">{d.badge}</p><h1>{d.title}</h1><p className="hero-copy">{d.subtitle}</p><div className="hero-actions"><a href="#healthcare-booking">{d.heroPrimary}</a><LocalizedLink locale={locale} href="/contact?industry=healthcare">{d.heroSecondary}</LocalizedLink></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[#487278]">{visual.heroTrust.map(item=><span key={item} className="flex items-center gap-2"><CheckCircle2 size={14} className="text-[#269989]"/>{item}</span>)}</div></div>
  <div className="relative pb-12 sm:pr-6"><div aria-hidden="true" className="healthcare-grid absolute -inset-6 rounded-[2.5rem]"/><div className="group relative aspect-[5/4] overflow-hidden rounded-[2rem] border border-[#123b45]/10 bg-[#dcebe9] shadow-[0_35px_90px_rgba(20,65,72,.2)]"><Image src="/images/industries/healthcare/modern-clinic-consultation-hero.jpg" alt={visual.heroAlt} fill priority sizes="(max-width: 1023px) calc(100vw - 2rem), 56vw" className="object-cover object-center transition-transform duration-700 group-hover:scale-[1.015]"/><div className="absolute inset-0 bg-linear-to-t from-[#10363d]/58 via-transparent to-transparent"/><div className="absolute left-4 top-4 rounded-full border border-white/50 bg-white/75 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#214950] backdrop-blur-md">{visual.demoState}</div></div><div className="healthcare-appointment absolute -bottom-1 left-3 right-0 rounded-2xl border border-[#17434a]/10 bg-white/96 p-4 text-[#17383e] shadow-2xl backdrop-blur-xl sm:left-auto sm:w-[27rem]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#dff2ee] text-[#168474]"><Stethoscope size={19}/></span><div className="min-w-0 flex-1"><p className="text-xs text-slate-500">{visual.appointmentLabel}</p><p className="truncate font-semibold">{visual.appointmentService}</p></div><CheckCircle2 className="text-[#168474]" size={20}/></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span><Building2 size={14}/>{visual.branch}</span><span><CalendarDays size={14}/>{visual.date}</span><span><Clock3 size={14}/>{visual.availableTime}</span><button type="button" aria-label={visual.bookAction}>{visual.bookAction}</button></div></div></div>
 </section>;
}
