import Image from "next/image";
import {Activity,Clock3,FlaskConical,HeartPulse,Search,SmilePlus} from "lucide-react";
import type {Dictionary} from "@/lib/i18n";
import {HealthcareReveal} from "./HealthcareReveal";

const icons=[HeartPulse,Activity,FlaskConical,SmilePlus];
export function ServiceCatalog({visual}:{visual:Dictionary["healthcareVisual"]}){
 return <HealthcareReveal className="healthcare-section"><div className="overflow-hidden rounded-[2rem] border border-[#173f46]/10 bg-[#113b43] text-white"><div className="grid lg:grid-cols-[1.15fr_.85fr]"><div className="p-6 sm:p-10 lg:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#77d0c2]">{visual.servicesEyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">{visual.servicesTitle}</h2><p className="mt-5 max-w-xl leading-8 text-[#b5cbcd]">{visual.servicesText}</p><div className="mt-7 flex min-h-12 items-center gap-3 rounded-xl border border-white/12 bg-white/7 px-4 text-sm text-[#bfd0d2]"><Search size={17}/>{visual.serviceSearch}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{visual.services.map((item,index)=>{const Icon=icons[index];return <article key={item} className="rounded-xl border border-white/10 bg-white/5 p-4"><Icon size={19} className="text-[#73cbbf]"/><p className="mt-4 font-semibold">{item}</p><p className="mt-2 flex items-center gap-2 text-xs text-[#aac2c4]"><Clock3 size={13}/>{visual.serviceDurations[index]}</p></article>})}</div><p className="mt-5 text-xs text-[#9fbabd]">{visual.servicesDisclaimer}</p></div><figure className="relative min-h-[28rem] overflow-hidden"><Image src="/images/industries/healthcare/dental-service-room.jpg" alt={visual.serviceAlt} fill sizes="(max-width: 1023px) calc(100vw - 2rem), 38vw" className="object-cover object-center"/><div className="absolute inset-0 bg-linear-to-t from-[#113b43]/65 via-transparent to-transparent"/><figcaption className="absolute bottom-5 left-5 right-5 rounded-xl border border-white/15 bg-[#113b43]/65 p-4 backdrop-blur-md"><p className="text-xs text-white/65">{visual.serviceImageLabel}</p><p className="mt-1 font-semibold">{visual.serviceImageValue}</p></figcaption></figure></div></div></HealthcareReveal>;
}
